package priority

const (
	PRIORITY_LABEL_PRIORITY_VERY_HIGH = "Priority: Very High"
	PRIORITY_LABEL_PRIORITY_HIGH      = "Priority: High"
	PRIORITY_LABEL_PRIORITY_MEDIUM    = "Priority: Medium"
	PRIORITY_LABEL_PRIORITY_LOW       = "Priority: Low"

	DEADLINE_TYPE_HOURS = "hours"
	DEADLINE_TYPE_DAYS  = "days"

	DEADLINE_LABEL_PRIORITY_VERY_HIGH = "Deadline: 24 hours"
	DEADLINE_LABEL_PRIORITY_HIGH      = "Deadline: 3 days"
	DEADLINE_LABEL_PRIORITY_MEDIUM    = "Deadline: 15 days"
	DEADLINE_LABEL_PRIORITY_LOW       = "Deadline: 60 days"
	DEADLINE_LABEL_OVERDUE            = "Deadline: Overdue"

	DEDUCE_NON_WORK_HOURS_PRIORITY_VERY_HIGH = false
	DEDUCE_NON_WORK_HOURS_PRIORITY_HIGH      = true
	DEDUCE_NON_WORK_HOURS_PRIORITY_MEDIUM    = true
	DEDUCE_NON_WORK_HOURS_PRIORITY_LOW       = true
)
