#!/bin/bash

# ngrok
export NGROK_STANDARD_PORT="8080"

# holidays
export HOLIDAY_API_URL="https://holidayapi.pl/v1/holidays"

# github
export GITHUB_API_URL="https://api.github.com"
export GITHUB_REPOSITORY_OWNER="flavioltonon"
export GITHUB_REPOSITORY_NAME="go-chronos"