package chronos

const (
	GITHUB_API_URL          = "https://api.github.com"
	GITHUB_REPOSITORY_OWNER = "flavioltonon"
	GITHUB_REPOSITORY_NAME  = "go-chronos"

	STANDARD_TIME_LOCATION = "America/Sao_Paulo"

	WORK_HOURS_INITIAL = 9
	WORK_HOURS_FINAL   = 18

	PRIORITY_LABEL_SIGNATURE = "Priority"
	// PRIORITY_LABEL_PRIORITY_VERY_HIGH = "Priority: Very High"
	// PRIORITY_LABEL_PRIORITY_HIGH      = "Priority: High"
	// PRIORITY_LABEL_PRIORITY_MEDIUM    = "Priority: Medium"
	// PRIORITY_LABEL_PRIORITY_LOW       = "Priority: Low"

	DEADLINE_TYPE_HOURS = "hours"
	DEADLINE_TYPE_DAYS  = "days"

	DEADLINE_LABEL_SIGNATURE = "Deadline"
	// DEADLINE_LABEL_PRIORITY_VERY_HIGH = "Deadline: 24 hours"
	// DEADLINE_LABEL_PRIORITY_HIGH      = "Deadline: 3 days"
	// DEADLINE_LABEL_PRIORITY_MEDIUM    = "Deadline: 15 days"
	// DEADLINE_LABEL_PRIORITY_LOW       = "Deadline: 60 days"
	DEADLINE_LABEL_OVERDUE = "Deadline: Overdue"

	// DEDUCE_NON_WORK_HOURS_PRIORITY_VERY_HIGH = false
	// DEDUCE_NON_WORK_HOURS_PRIORITY_HIGH      = true
	// DEDUCE_NON_WORK_HOURS_PRIORITY_MEDIUM    = true
	// DEDUCE_NON_WORK_HOURS_PRIORITY_LOW       = true

	COLUMN_BACKLOG        = "Backlog"
	COLUMN_SPRINT_BACKLOG = "Sprint backlog"
	COLUMN_ONGOING        = "Ongoing"
	COLUMN_PULL_REQUEST   = "Pull Request"
	COLUMN_DONE_SPRINT    = "Done (sprint)"
	COLUMN_DONE           = "Done"

	STANDARD_ISSUE_STATE_COLUMN_BACKLOG        = "open"
	STANDARD_ISSUE_STATE_COLUMN_SPRINT_BACKLOG = "open"
	STANDARD_ISSUE_STATE_COLUMN_ONGOING        = "open"
	STANDARD_ISSUE_STATE_COLUMN_PULL_REQUEST   = "open"
	STANDARD_ISSUE_STATE_COLUMN_DONE_SPRINT    = "closed"
	STANDARD_ISSUE_STATE_COLUMN_DONE           = "closed"

	STATUS_LABEL_SIGNATURE      = "Status"
	STATUS_LABEL_BACKLOG        = ""
	STATUS_LABEL_ONGOING        = ""
	STATUS_LABEL_SPRINT_BACKLOG = ""
	STATUS_LABEL_PULL_REQUEST   = "Status: PR/Tests"
	STATUS_LABEL_DONE_SPRINT    = ""
	STATUS_LABEL_DONE           = ""

	HOLIDAY_API_URL = "https://holidayapi.pl/v1/holidays"
)
